main: me.sudologic.elytradogfights.Main
name: ElytraDogfights
description: Setup and run the ElytraDogfights minigame by sudologic
version: 1.5.4
author: sudologic
api-version: 1.18
commands:
  SoloStartGame:
    description: Starts an ElytraDogfights Solo game
    usage: /SoloStartGame
  TeamsStartGame:
    description: Starts an ElytraDogfights Teams game
    usage: /TeamsStartGame
  Leave:
    description: Exits an ElytraDogfights game.
    usage: /Leave
  ToggleGameIsRunning:
    description: Toggles the variable gameIsRunning, used for debugging.
    usage: /ToggleGameIsRunning