main: me.sudologic.elytradogfights.Main
name: ElytraDogfights
description: Setup and run the ElytraDogfights minigame by sudologic
version: 1.5.3
author: sudologic
api-version: 1.18
commands:
  FFAStartGame:
    description: Starts an ElytraDogfights Free For All game
    usage: /FFAStartGame
  TeamsStartGame:
    description: Starts an ElytraDogfights Teams game
    usage: /TeamsStartGame
  Leave:
    description: Exits an ElytraDogfights game.
    usage: /Leave
  ToggleGameIsRunning:
    description: Toggles the variable gameIsRunning, used for debugging.
    usage: /ToggleGameIsRunning